### ISSUE TITLE
A query regarding n_potentials option in the toml file

### ISSUE THREAD

**Issue by Youhaojen** [initqp/somd_tutorials#2]
Dear @initqp ,

I wanted to take a moment to express my sincere appreciation for the excellent work you have done. Your efforts have truly been exceptional, and the results are nothing short of amazing. Thank you!

Additionally, I have a question regarding the `n_potentials` option in the toml file, as mentioned in your tutorial where you set `n_potentials = 4` to create four different potentials. I'm curious to know the specific differences among these four potentials. Are they determined by the random seed, similar to how DP-GEN operates?

Thank you once again for your outstanding work, and I look forward to your response.

Warm regards,
Hao-Jen You

**Comment by initqp** [comment]
Dear Youhaojen,

You are completely right about the `n_potentials` option. In SOMD, training of different potentials is done by simply invoking `nep` multiple times. Since the seed (initial weights) of a `nep`  training process is random, the four potentials will be different, just as in the DP-GEN package.

Best regards

**Comment by initqp** [comment]
I also would like to remind you that I will update these tutorials in the following few days since I have merged https://github.com/initqp/somd/pull/6 to master. The only difference between before and after the merging is that the files that recode the training process have changed (from the `training_iter_i/training_info.json`  files to the one `prefix.active_learning.h5` file). If you still need the old text, you could view them from [this branch](https://github.com/initqp/somd_tutorials/tree/somd-0.1.2). I am sorry about the inconvenience, if you have any other problems, please feel free to open new issues.
